import { readFile, writeFile, rm, mkdir, copyFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(process.cwd(), "dist/wasm/web");
const srcShimDir = path.resolve(process.cwd(), "src/wasm/web");
const wasmPath = path.join(root, "bridge_wasm_bg.wasm");
const gluePath = path.join(root, "bridge_wasm.js");
const glueDtsPath = path.join(root, "bridge_wasm.d.ts");
const inlinePath = path.join(root, "bridge_wasm_inline.js");
const inlineDtsPath = path.join(root, "bridge_wasm_inline.d.ts");
const stalePackageJson = path.join(root, "package.json");

async function emitInline() {
  const bytes = await readFile(wasmPath);
  const b64 = bytes.toString("base64");
  const js = `// AUTO-GENERATED by scripts/postprocess-wasm.mjs\nexport const wasmBase64 = ${JSON.stringify(b64)};\n`;
  const dts = `export declare const wasmBase64: string;\n`;
  await writeFile(inlinePath, js, "utf8");
  await writeFile(inlineDtsPath, dts, "utf8");
  console.log(`[postprocess-wasm] wrote ${path.relative(process.cwd(), inlinePath)} (${bytes.length} bytes -> ${b64.length} chars base64)`);
}

async function patchGlue() {
  const original = await readFile(gluePath, "utf8");
  // Remove the `new URL('bridge_wasm_bg.wasm', import.meta.url)` pattern that
  // bundlers statically analyze. Replace the entire `if (module_or_path === undefined)`
  // block with an explicit error since callers must always pass bytes.
  const patched = original.replace(
    /if \(module_or_path === undefined\) \{[\s\S]*?\}\n/,
    `if (module_or_path === undefined) {\n        throw new Error("tachybridge-wasm: pass wasm bytes via { module_or_path } explicitly; auto-fetch was removed for bundler compatibility");\n    }\n`
  );
  if (patched === original) {
    throw new Error("[postprocess-wasm] failed to patch bridge_wasm.js — expected `if (module_or_path === undefined)` block not found. wasm-pack output may have changed.");
  }
  await writeFile(gluePath, patched, "utf8");
  console.log(`[postprocess-wasm] patched ${path.relative(process.cwd(), gluePath)} (removed static asset URL)`);
}

async function dropStalePackageJson() {
  // wasm-pack writes its own package.json which conflicts with our exports map.
  await rm(stalePackageJson, { force: true });
  await rm(path.resolve(process.cwd(), "dist/wasm/node/package.json"), { force: true });
  console.log(`[postprocess-wasm] removed nested package.json files`);
}

async function dropWasmPackGitignores() {
  // wasm-pack writes a `.gitignore` with `**` into each output dir. npm pack
  // honors it and silently drops the whole wasm/ tree from the published
  // tarball — exactly what bit us once already.
  await rm(path.join(root, ".gitignore"), { force: true });
  await rm(path.resolve(process.cwd(), "dist/wasm/node/.gitignore"), { force: true });
  console.log(`[postprocess-wasm] removed wasm-pack .gitignore stubs`);
}

async function dropWasmBinary() {
  // The .wasm is now embedded in bridge_wasm_inline.js as base64; the binary
  // file is no longer needed at runtime and would only inflate the tarball.
  await rm(wasmPath, { force: true });
  console.log(`[postprocess-wasm] removed ${path.relative(process.cwd(), wasmPath)}`);
}

async function copyShimsIntoSrc() {
  // tsc is invoked with rootDir: "src" so it cannot reach into dist/. Copy
  // both .d.ts (so tsc resolves the static imports in src/browser.ts) and
  // .js (so vitest, which runs against src/, can import them at runtime)
  // into src/wasm/web/. tsc with allowJs:false ignores the .js copies so
  // they never end up in dist/. At publish time the runtime relative path
  // from dist/browser.js resolves to dist/wasm/web/bridge_wasm.js as built.
  await mkdir(srcShimDir, { recursive: true });
  await copyFile(glueDtsPath, path.join(srcShimDir, "bridge_wasm.d.ts"));
  await copyFile(inlineDtsPath, path.join(srcShimDir, "bridge_wasm_inline.d.ts"));
  await copyFile(gluePath, path.join(srcShimDir, "bridge_wasm.js"));
  await copyFile(inlinePath, path.join(srcShimDir, "bridge_wasm_inline.js"));
  console.log(`[postprocess-wasm] copied shims into ${path.relative(process.cwd(), srcShimDir)} (.d.ts + .js)`);
}

await emitInline();
await patchGlue();
await copyShimsIntoSrc();
await dropStalePackageJson();
await dropWasmPackGitignores();
await dropWasmBinary();
